### For reference, see `nextepc.conf`

logger:
  file: /usr/local/var/log/open5gs/pgw.log
  trace: 
      app: 1
      diameter: 1
      gtpv2: 1
      gtp: 1

parameter:
  no_ipv6: true

pgw:
  freeDiameter: /usr/local/etc/freeDiameter/pgw.conf
  gtpc:
    addr:
      - 192.168.26.40
      #- ::1
  gtpu:
    - addr: 192.168.26.40
    #- addr: ::1
  ue_pool:
    - addr: 45.45.0.1/16
    #- addr: cafe::1/64
  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844

